language: cpp
install:
  - sudo apt-get install -y libgtest-dev
  - cd /usr/src/gtest
  - sudo env "PATH=$PATH" cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib
  - cd "${TRAVIS_BUILD_DIR}"

before_script:
  
script:
  - cmake .
  - cmake --build .
  - cmake --build . --target test
  - cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T helloworld-1.1.$TRAVIS_BUILD_NUMBER-Linux.deb -upetrljutik:$BINTRAY_API_KEY https://api.bintray.com/content/petrljutik/helloworld/helloworld/$TRAVIS_BUILD_NUMBER/helloworld-1.1.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"