language: cpp
install:
  - sudo apt-get install libgtest-dev
  - cd /usr/src/gtest
  - sudo env PATH=$PATH cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib

before_script:
  
script:
  - cmake .
  - cmake --build .
  - cmake --build . --target test